INSERT INTO categories (id, name_tr, name_en, slug, sort_order) VALUES
('aydinlatma-grubu','Aydınlatma Grubu','Lighting Group','aydinlatma-grubu',1),
('basamaklar','Basamaklar','Footrests','basamaklar',2),
('dis-aksam','Dış Aksam','Body Parts','dis-aksam',3),
('disliler','Dişliler','Gears','disliler',4),
('elektrik-grubu','Elektrik Grubu','Electrical Group','elektrik-grubu',5),
('egzoz-grubu','Egzoz Grubu','Exhaust Group','egzoz-grubu',6),
('fren-balata-grubu','Fren Balata Grubu','Brake Pad Group','fren-balata-grubu',7),
('gidon-aksamlari','Gidon Aksamları','Handlebar Parts','gidon-aksamlari',8),
('kilometre-saatleri','Kilometre Saatleri','Speedometers','kilometre-saatleri',9),
('kilitler','Kilitler','Locks','kilitler',10),
('koruma-ekipmanlari','Koruma Ekipmanları','Protective Equipment','koruma-ekipmanlari',11),
('motor-aksami','Motor Aksamı','Engine Parts','motor-aksami',12),
('motosiklet-aksesuarlari','Motosiklet Aksesuarları','Motorcycle Accessories','motosiklet-aksesuarlari',13),
('motosiklet-telleri','Motosiklet Telleri','Motorcycle Cables','motosiklet-telleri',14),
('on-arka-teker-grubu','Ön - Arka Teker Grubu','Front & Rear Wheel Group','on-arka-teker-grubu',15),
('pedal-ve-sehpa','Pedal ve Sehpa','Pedals & Stand','pedal-ve-sehpa',16),
('tamir-aparatlari','Tamir Aparatları','Repair Tools','tamir-aparatlari',17),
('zincirler-ve-zincir-disli-setleri','Zincirler ve Zincir Dişli Setleri','Chains & Sprocket Sets','zincirler-ve-zincir-disli-setleri',18),
('avantajli-set-urunler','Avantajlı Set Ürünler','Value Bundle Products','avantajli-set-urunler',19)
ON CONFLICT (id) DO NOTHING;

INSERT INTO subcategories (id, category_id, name_tr, name_en, slug) VALUES
('far-grubu','aydinlatma-grubu','Far Grubu','Headlight Group','far-grubu'),
('stop-lambasi','aydinlatma-grubu','Stop Lambası','Tail Light','stop-lambasi'),
('sinyal-grubu','aydinlatma-grubu','Sinyal Grubu','Turn Signal Group','sinyal-grubu'),
('ampul-ve-led','aydinlatma-grubu','Ampul ve LED','Bulbs & LED','ampul-ve-led'),
('sis-fari','aydinlatma-grubu','Sis Farı','Fog Light','sis-fari'),
('alarm','aydinlatma-grubu','Alarm','Alarm','alarm'),
('surucu-basamagi','basamaklar','Sürücü Basamağı','Rider Footrest','surucu-basamagi'),
('yolcu-basamagi','basamaklar','Yolcu Basamağı','Passenger Footrest','yolcu-basamagi'),
('basamak-kaucugu','basamaklar','Basamak Kauçuğu','Footrest Rubber','basamak-kaucugu'),
('grenaj','dis-aksam','Grenaj','Fairing','grenaj'),
('camurluk','dis-aksam','Çamurluk','Fender','camurluk'),
('depo-kapagi','dis-aksam','Depo Kapağı','Tank Cover','depo-kapagi'),
('yan-panel','dis-aksam','Yan Panel','Side Panel','yan-panel'),
('benzin-deposu','dis-aksam','Benzin Deposu','Fuel Tank','benzin-deposu'),
('sele','dis-aksam','Sele','Seat','sele'),
('paspas','dis-aksam','Paspas & Ayak Tabanı','Floor Mat & Footboard','paspas'),
('koruma-demiri','dis-aksam','Koruma Demiri','Crash Guard','koruma-demiri'),
('siperlik-cami','dis-aksam','Siperlik Camı','Windshield','siperlik-cami'),
('sanziman-dislisi','disliler','Şanzıman Dişlisi','Transmission Gear','sanziman-dislisi'),
('hiz-dislisi','disliler','Hız Dişlisi','Speed Gear','hiz-dislisi'),
('devirdaim-dislisi','disliler','Devirdaim Dişlisi','Drive Gear','devirdaim-dislisi'),
('bujiler','elektrik-grubu','Bujiler','Spark Plugs','bujiler'),
('aku','elektrik-grubu','Akü','Battery','aku'),
('atesleme-bobini','elektrik-grubu','Ateşleme Bobini','Ignition Coil','atesleme-bobini'),
('cdi','elektrik-grubu','CDI & İgnisyon','CDI & Ignition Unit','cdi'),
('rotor-stator','elektrik-grubu','Rotor & Statör','Rotor & Stator','rotor-stator'),
('konjektur','elektrik-grubu','Konjektör','Fuel Injector','konjektur'),
('mars-motoru','elektrik-grubu','Marş Motoru','Starter Motor','mars-motoru'),
('kablo-tesisati','elektrik-grubu','Kablo Tesisatı','Wiring Harness','kablo-tesisati'),
('egzoz','egzoz-grubu','Egzoz','Exhaust','egzoz'),
('egzoz-contasi','egzoz-grubu','Egzoz Contası','Exhaust Gasket','egzoz-contasi'),
('egzoz-baglanti-aparatlari','egzoz-grubu','Egzoz Bağlantı Aparatları','Exhaust Mounting Hardware','egzoz-baglanti-aparatlari'),
('disk-balatasi','fren-balata-grubu','Disk Balatası','Disc Brake Pad','disk-balatasi'),
('fren-balatasi','fren-balata-grubu','Fren Balatası','Brake Pad','fren-balatasi'),
('disk-tepsisi','fren-balata-grubu','Disk Tepsisi','Brake Rotor','disk-tepsisi'),
('gidon','gidon-aksamlari','Gidon','Handlebar','gidon'),
('gidon-kaucugu','gidon-aksamlari','Gidon Kauçuğu','Handlebar Grip','gidon-kaucugu'),
('direksiyon-kolu','gidon-aksamlari','Direksiyon Kolu','Control Lever','direksiyon-kolu'),
('analog-gosterge','kilometre-saatleri','Analog Gösterge','Analog Gauge','analog-gosterge'),
('dijital-gosterge','kilometre-saatleri','Dijital Gösterge','Digital Gauge','dijital-gosterge'),
('kilometre-sensoru','kilometre-saatleri','Kilometre Sensörü','Speed Sensor','kilometre-sensoru'),
('kontak-kilidi','kilitler','Kontak Kilidi','Ignition Lock','kontak-kilidi'),
('depo-kilidi','kilitler','Depo Kilidi','Fuel Cap Lock','depo-kilidi'),
('koltuk-kilidi','kilitler','Koltuk Kilidi','Seat Lock','koltuk-kilidi'),
('motor-koruyucu','koruma-ekipmanlari','Motor Koruyucu','Engine Guard','motor-koruyucu'),
('el-korumaligi','koruma-ekipmanlari','El Korumalığı','Hand Guard','el-korumaligi'),
('piston','motor-aksami','Piston','Piston','piston'),
('segman','motor-aksami','Segman','Piston Ring','segman'),
('silindir','motor-aksami','Silindir','Cylinder','silindir'),
('conta-takimi','motor-aksami','Conta Takımı','Gasket Set','conta-takimi'),
('supap','motor-aksami','Supap','Valve','supap'),
('yag-filtresi','motor-aksami','Yağ Filtresi','Oil Filter','yag-filtresi'),
('hava-filtresi','motor-aksami','Hava Filtresi','Air Filter','hava-filtresi'),
('karburator','motor-aksami','Karbüratör','Carburetor','karburator'),
('kayis','motor-aksami','Kayış','Drive Belt','kayis'),
('krank','motor-aksami','Krank & Biyel','Crankshaft & Con Rod','krank'),
('kece','motor-aksami','Keçeler','Oil Seals','kece'),
('dikiz-aynasi','motosiklet-aksesuarlari','Dikiz Aynası','Rear View Mirror','dikiz-aynasi'),
('arka-tasiyici','motosiklet-aksesuarlari','Arka Taşıyıcı','Rear Carrier','arka-tasiyici'),
('korna','motosiklet-aksesuarlari','Korna','Horn','korna'),
('gaz-teli','motosiklet-telleri','Gaz Teli','Throttle Cable','gaz-teli'),
('debriyaj-teli','motosiklet-telleri','Debriyaj Teli','Clutch Cable','debriyaj-teli'),
('fren-teli','motosiklet-telleri','Fren Teli','Brake Cable','fren-teli'),
('kilometre-teli','motosiklet-telleri','Kilometre Teli','Speedometer Cable','kilometre-teli'),
('amortisor-on','on-arka-teker-grubu','Ön Amortisör','Front Shock Absorber','amortisor-on'),
('amortisor-arka','on-arka-teker-grubu','Arka Amortisör','Rear Shock Absorber','amortisor-arka'),
('jant','on-arka-teker-grubu','Jant','Rim','jant'),
('kampana','on-arka-teker-grubu','Kampana','Brake Drum','kampana'),
('rulman','on-arka-teker-grubu','Rulman','Bearing','rulman'),
('aks-mili','on-arka-teker-grubu','Aks Mili','Axle Shaft','aks-mili'),
('teker-baglanti-parcalari','on-arka-teker-grubu','Teker Bağlantı Parçaları','Wheel Mounting Parts','teker-baglanti-parcalari'),
('fren-pedali','pedal-ve-sehpa','Fren Pedalı','Brake Pedal','fren-pedali'),
('vites-pedali','pedal-ve-sehpa','Vites Pedalı','Gear Pedal','vites-pedali'),
('yan-sehpa','pedal-ve-sehpa','Yan Sehpa','Side Stand','yan-sehpa'),
('merkez-sehpa','pedal-ve-sehpa','Merkez Sehpa','Center Stand','merkez-sehpa'),
('piston-aparati','tamir-aparatlari','Piston Aparatı','Piston Tool','piston-aparati'),
('conta-seti','tamir-aparatlari','Conta Seti','Gasket Tool Set','conta-seti'),
('rulman-aparati','tamir-aparatlari','Rulman Aparatı','Bearing Tool','rulman-aparati'),
('zincir','zincirler-ve-zincir-disli-setleri','Zincir','Chain','zincir'),
('on-disli','zincirler-ve-zincir-disli-setleri','Ön Dişli','Front Sprocket','on-disli'),
('arka-disli','zincirler-ve-zincir-disli-setleri','Arka Dişli','Rear Sprocket','arka-disli'),
('zincir-disli-seti','zincirler-ve-zincir-disli-setleri','Zincir Dişli Seti','Chain Sprocket Kit','zincir-disli-seti'),
('zincir-kilidi','zincirler-ve-zincir-disli-setleri','Zincir Kilidi','Chain Link','zincir-kilidi'),
('bakim-seti','avantajli-set-urunler','Bakım Seti','Maintenance Set','bakim-seti'),
('motor-revizyon-seti','avantajli-set-urunler','Motor Revizyon Seti','Engine Overhaul Kit','motor-revizyon-seti'),
('fren-bakim-seti','avantajli-set-urunler','Fren Bakım Seti','Brake Service Kit','fren-bakim-seti'),
('zincir-bakim-seti','avantajli-set-urunler','Zincir Bakım Seti','Chain Service Kit','zincir-bakim-seti')
ON CONFLICT (id) DO NOTHING;
